name: MRPGNPC
author: MuffinHead
main: com.muffinhead.MRPGNPC.MRPGNPC
load: POSTWORLD
api: "1.0.8"
version: "1.1.3"
commands:
  mrn:
    description: "mrn"
    permission: commands.muffinhead.MRPGNPC
permissions:
  commands.muffinhead.MRPGNPC:
    default: op